---
- name: "Configure HAProxy Load Balancer"
  hosts: loadbalancers
  become: yes

  tasks:
    - name: "Install HAProxy"
      apt:
        name: haproxy 
        state: present

    - name: "Check if SSL certificate exists"
      stat:
        path: "/etc/haproxy/certs/{{ ansible_host }}.nip.io.pem"
      register: ssl_cert_file

    - name: Push dynamic config file
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: "Restart HAProxy"

    - name: "Push dynamic config file"
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: "Restart HAProxy" 

    - name: "Ensure HAProxy is enabled on boot"
      systemd:
        name: haproxy
        state: started 

    - name: "Allow HTTP/HTTPS through UFW"
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '80'
        - '443'
        
  handlers:
    - name: "Restart HAProxy"
      systemd:
        name: haproxy
        state: restarted
