---
- name: Monitoring Tools Install
  hosts: loadbalancers
  become: yes

  vars_files:
    - secrets.yml

  tasks:
    - name: Install Prometheus and Alertmanager
      apt:
        name: 
          - prometheus
          - prometheus-alertmanager
        state: present

    - name: Install Grafana using direct link
      apt:
        deb: "https://dl.grafana.com/oss/release/grafana_10.4.1_amd64.deb"

    - name: Push Prometheus Alerting Rules
      copy:
        src: templates/alert.rules.yml
        dest: /etc/prometheus/alert.rules.yml
      notify: "Restart Prometheus"

    - name: Push Alertmanager Config
      template:
        src: templates/alertmanager.yml.j2
        dest: /etc/prometheus/alertmanager.yml
      notify: "Restart Alertmanager"

    - name: Push the Prometheus Config
      template: 
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify: "Restart Prometheus"

    - name: "Enable Observability stack on boot"
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - prometheus
        - grafana-server
        - prometheus-alertmanager

    - name: "Open UFW for Grafana"
      ufw:
        rule: allow
        port: '3000'
        proto: tcp

  handlers:
    - name: "Restart Prometheus"
      systemd:
        name: prometheus
        state: restarted

    - name: "Restart Alertmanager"
      systemd:
        name: prometheus-alertmanager
        state: restarted