name: Ansible CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

# JOB 1: CONTINUOUS INTEGRATION (TESTING)

  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Syntax Check All Playbooks
        run: |
          ansible-playbook -i ansible/inventory.ini.example ansible/base.yml --syntax-check
          ansible-playbook -i ansible/inventory.ini.example ansible/haproxy.yml --syntax-check
          ansible-playbook -i ansible/inventory.ini.example ansible/web.yml --syntax-check
          ansible-playbook -i ansible/inventory.ini.example ansible/postgres.yml --syntax-check

# JOB 2: CONTINUOUS DEPLOYMENT

  deploy-to-aws:
    needs: syntax-check
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible
      
      - name: Setup SSH Key and Inventory
        run:
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          echo "${{ secrets.ANSIBLE_INVENTORY }}" > inventory.ini

      - name: DeployWeb Tier
        run: ansible-playbook -i inventory.ini ansible/web.yml
